spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 500
        response-timeout: 5s
        ssl:
          useInsecureTrustManager: true
      routes:
        - id: USER-SERVICE
          uri: https://www.google.com
          predicates:
            - Path=/v1/**
          metadata:
            - connect-timeout: 500
            - response-timeout: 2s
          filters:
            - RewritePath=/v1/(?<segment>.*),/
            - AuthPreFilter
            - CommonPostFilter
