spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      routes:
        - id: USER-SERVICE
          uri: https://www.google.com
          predicates:
            - Path=/v1/**
          filters:
            - RewritePath=/v1/(?<segment>.*),/
            - AuthPreFilter
            - CommonPostFilter